// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock.API.Models;

#nullable disable

namespace Stock.API.Migrations
{
    [DbContext(typeof(StockAPIDbContext))]
    [Migration("20241030104813_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stock.API.Models.Entities.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d599532-8f90-463f-8c9c-13c629c8d6cd"),
                            Count = 2000,
                            ProductId = new Guid("6b6385cd-19cc-4d55-ae4f-2c88afae44d9")
                        },
                        new
                        {
                            Id = new Guid("86dbb111-6e34-4ef3-ac42-fba753041f51"),
                            Count = 1000,
                            ProductId = new Guid("12c66184-6ca2-445a-ab51-4394f654881e")
                        },
                        new
                        {
                            Id = new Guid("a6afa32f-f469-4063-af2a-0b21ae4cfe18"),
                            Count = 3000,
                            ProductId = new Guid("e237c625-ae53-4fe5-9fdc-5bc681a51d18")
                        },
                        new
                        {
                            Id = new Guid("f075dfdf-9e8f-41fd-81df-b3e758000083"),
                            Count = 5000,
                            ProductId = new Guid("89de26b2-665c-4d96-b67d-c974958f2dd3")
                        },
                        new
                        {
                            Id = new Guid("a6eae1ff-f371-421b-9110-80ae265ba4e6"),
                            Count = 500,
                            ProductId = new Guid("20140d95-12d8-4b4e-8c1a-b300a63b2e33")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
